markdown: kramdown
highlighter: rouge

permalink: pretty
url: https://steve.arguiot.com

github: https://github.com/arguiot
twitter: https://twitter.com/arthur_guiot
discord: https://discord.gg

title: Title
description: Description
hero-image: https://source.unsplash.com/random
logo: https://arguiot.com/img/logo.png

copyright: Arthur Guiot

menu:
  - url: https://steve.arguiot.com
    name: Page 1