markdown: kramdown
highlighter: rouge

permalink: pretty
url: https://steve.arguiot.com

title: Title
description: Description
hero-image: https://source.unsplash.com/random
logo: https://arguiot.com/img/logo.png

copyright: Arthur Guiot

menu:
  - url: https://steve.arguiot.com
    name: Page 1