markdown: kramdown
highlighter: rouge

permalink: pretty
url: https://tim.arguiot.com

github: https://github.com/arguiot
twitter: https://twitter.com/arthur_guiot
discuss: https://discord.gg

title: Tim
description: A jekyll theme for tech lovers, developers and designers
hero-image: https://source.unsplash.com/random
logo: https://arguiot.com/img/logo.png

copyright: Arthur Guiot

menu:
  - url: https://tim.arguiot.com
    name: Page 1